In [15]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
import sys
sys.path.append("..")
#import os
from utils.model import Net_mask
import torch
#import numpy as np
import matplotlib.pyplot as plt
from torch.distributions.multivariate_normal import MultivariateNormal

In [17]:
model_ML_inf = Net_mask()
model_MAP_e4 = Net_mask()
model_MAP_e4_0 = Net_mask()
model_MAP_e4_1 = Net_mask()
model_MAP_e4_2 = Net_mask()
model_MAP_e4_3 = Net_mask()
model_MAP_e4_4 = Net_mask()
model_MAP_e4_R100 = Net_mask()
model_MAP_e5 = Net_mask()
model_MAP_e5_0 = Net_mask()
model_MAP_e5_1 = Net_mask()
model_MAP_e5_2 = Net_mask()
model_MAP_e5_3 = Net_mask()
model_MAP_e5_4 = Net_mask()
model_MAP_e6 = Net_mask()
model_MAP_e6_R100 = Net_mask()
model_ML_inf_reg = Net_mask()
model_ML_inf_reg_10 = Net_mask()

#model_ML_inf.load_state_dict(torch.load(f'../saved_models/models_infinite_data/ML/model_weights.pth'))
#model_MAP_e4.load_state_dict(torch.load(f'../saved_models/finite_long_e4/map/0/model_weights.pth'))
#model_MAP_e4_R100.load_state_dict(torch.load(f'../saved_models/finite_long_e4_100/map/0/model_weights.pth'))
#model_MAP_e5.load_state_dict(torch.load(f'../saved_models/finite_long_e5/map/0/model_weights.pth'))
#model_MAP_e6.load_state_dict(torch.load(f'../saved_models/finite_long_e6/map/0/model_weights.pth'))
#model_MAP_e6_R100.load_state_dict(torch.load(f'../saved_models/finite_long_e6_100/map/0/model_weights.pth'))
#model_ML_inf_reg.load_state_dict(torch.load(f'../saved_models/models_infinite_data/MAP_inf_prior_100/model_weights.pth'))
#model_ML_inf_reg_10.load_state_dict(torch.load(f'../saved_models/models_infinite_data/MAP_inf_prior_10/model_weights.pth'))
model_MAP_e4_0.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e4/0/model_weights.pth'))
model_MAP_e4_1.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e4/1/model_weights.pth'))
model_MAP_e4_2.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e4/2/model_weights.pth'))
model_MAP_e4_3.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e4/3/model_weights.pth'))
model_MAP_e4_4.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e4/4/model_weights.pth'))
model_MAP_e5_0.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e5/0/model_weights.pth'))
model_MAP_e5_1.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e5/1/model_weights.pth'))
model_MAP_e5_2.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e5/2/model_weights.pth'))
model_MAP_e5_3.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e5/3/model_weights.pth'))
model_MAP_e5_4.load_state_dict(torch.load(f'../saved_models/testing/map2/long/e5/4/model_weights.pth'))


model_ML_inf.load_state_dict(torch.load(f'../saved_models/models_infinite_data/ML/model_weights.pth'))
model_ML_inf_reg.load_state_dict(torch.load(f'../saved_models/models_infinite_data/MAP_inf_prior_100/model_weights.pth'))
model_ML_inf_reg_10.load_state_dict(torch.load(f'../saved_models/models_infinite_data/MAP_inf_prior_10/model_weights.pth'))
#model_MAP_e4.load_state_dict(torch.load(f'../saved_models/models_finite_data/e4/prior_10/model_weights.pth'))
model_MAP_e4.load_state_dict(torch.load(f'../saved_models/testing/map/long/e4/0/model_weights.pth'))
model_MAP_e4_R100.load_state_dict(torch.load(f'../saved_models/models_finite_data/e4/prior_100/model_weights.pth'))
#model_MAP_e5.load_state_dict(torch.load(f'../saved_models/models_finite_data/e5/prior_100/model_weights.pth'))
model_MAP_e5.load_state_dict(torch.load(f'../saved_models/testing/map/long/e5/0/model_weights.pth'))
model_MAP_e6.load_state_dict(torch.load(f'../saved_models/models_finite_data/e6/prior_1000/model_weights.pth'))
model_MAP_e6_R100.load_state_dict(torch.load(f'../saved_models/models_finite_data/e6/prior_100/model_weights.pth'))

<All keys matched successfully>

In [18]:
tensor_D = torch.tensor(
    [[1, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, -1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0,  1, -1, 0, 0, 0, 0, 0, 0],
    [0, 0,  0, 1, -1, 0, 0, 0, 0, 0],
    [0, 0,  0, 0, 1, -1, 0, 0, 0, 0],
    [0, 0,  0, 0, 0, 1, -1, 0, 0, 0],
    [0, 0,  0, 0, 0, 0, 1, -1, 0, 0],
    [0, 0,  0, 0, 0, 0, 0, 1, -1, 0],
    [0, 0,  0, 0, 0, 0, 0, 0, 1, -1],
    [-1, 0, 0, 0, 0, 0, 0, 0, 0, 1],], dtype=torch.float
)
tensor_Q_m  = torch.mm(torch.t(tensor_D), tensor_D)
n_param = tensor_D.size(dim=0)
#tau2 = 1000 # 1/tau2 is the noise added to the diagonal
#tensor_Q_m_modified = tensor_Q_m + torch.eye(n_param)*(1./tau2)
#sigma2_eps = 0.01  # 1/sigma2_eps is the factor before the likelihood
#tensor_mu_m = torch.zeros(n_param)

#tensor_Sigma_m = torch.inverse(tensor_Q_m_modified)
#tensor_Sigma_eps = torch.eye(n_param)*sigma2_eps
#tensor_mu_eps = tensor_mu_m 

In [19]:
all_test_obses = torch.load(f'../data/test_observations/test_set_full/all_test_obses.pt')
all_test_solutions = torch.load(f'../data/test_observations/test_set_full/all_test_solutions.pt')

In [20]:
def loss(predicted, analytical):
    difference = predicted - analytical
    squared_error = torch.square(difference)
    tensor_squared_error_sum = torch.sum(squared_error, dim=1)
    tensor_squared_error_sum_all = torch.sum(tensor_squared_error_sum)
    return tensor_squared_error_sum_all

In [21]:
max_points = 6
n_data = all_test_obses.shape[1]

#f_list = list(range(0, 20)) + list(range(20, 28)) + list(range(60, 65)) + [81, 82] + list(range(96, 100))
#f_list = list(range(0, 19)) + list(range(20, 27)) + list(range(60, 65)) + [81, 82] + list(range(96, 100))
#f_list = list(range(31)) + list(range(60, 68)) + [70] + list(range(80, 85)) + list(range(92, 100))
#f_list = list(range(34)) + list(range(60, 72)) + list(range(80,88)) + list(range(92, 100))
f_list = list(range(48)) + list(range(51, 100)) 
f_length = len(f_list)
n_bnn = f_length
loss_RML_e4_all = torch.zeros(max_points, n_bnn)
loss_RML_e5_all = torch.zeros(max_points, n_bnn)

loss_ML_inf = torch.zeros(max_points)
loss_ML_inf_reg = torch.zeros(max_points)
loss_ML_inf_reg_10 = torch.zeros(max_points)
loss_MAP_e4 = torch.zeros(max_points)
loss_MAP_e4_R100 = torch.zeros(max_points)
loss_MAP_e5 = torch.zeros(max_points)
loss_MAP_e6 = torch.zeros(max_points)
loss_MAP_e6_R100 = torch.zeros(max_points)

loss_RML_e4_0 = torch.zeros(max_points)
loss_RML_e4_n_mean = torch.zeros(max_points)
loss_RML_e4_mean = torch.zeros(max_points)
loss_RML_e4_median = torch.zeros(max_points)
loss_RML_e4_variance = torch.zeros(max_points)
loss_RML_e5_0 = torch.zeros(max_points)
loss_RML_e5_n_mean = torch.zeros(max_points)
loss_RML_e5_mean = torch.zeros(max_points)
loss_RML_e5_median = torch.zeros(max_points)
loss_RML_e5_variance = torch.zeros(max_points)


loss_MAP_e4_0 = torch.zeros(max_points)
loss_MAP_e4_1 = torch.zeros(max_points)
loss_MAP_e4_2 = torch.zeros(max_points)
loss_MAP_e4_3 = torch.zeros(max_points)
loss_MAP_e4_4 = torch.zeros(max_points)
loss_MAP_e5_0 = torch.zeros(max_points)
loss_MAP_e5_1 = torch.zeros(max_points)
loss_MAP_e5_2 = torch.zeros(max_points)
loss_MAP_e5_3 = torch.zeros(max_points)
loss_MAP_e5_4 = torch.zeros(max_points)


for p in range(max_points):
    test_set_points = all_test_obses[p]
    test_set_solution = all_test_solutions[p]

    #i_list = list(range(26)) + list(range(83, 100))
    #i_list = list(range(12)) + list(range(96, 100))

    pred_RML_e4_all = torch.zeros(n_bnn, n_data, n_param)
    pred_RML_e5_all = torch.zeros(n_bnn, n_data, n_param)
    
    for idx, item in enumerate(f_list):
        model_RML_e4 = Net_mask()
        model_RML_e4.load_state_dict(torch.load(f'../saved_models/testing/rml/long/e4/{item}/model_weights.pth'))
        pred_RML_e4_all[idx] = model_RML_e4(test_set_points)
        loss_RML_e4_all[p,idx] = loss(pred_RML_e4_all[idx], test_set_solution)

    #i_list = list(range(35)) + list(range(92, 100))
    #i_list = list(range(12)) + list(range(96, 100))
    for idx, item in enumerate(f_list):
        model_RML_e5 = Net_mask()
        model_RML_e5.load_state_dict(torch.load(f'../saved_models/testing/rml/long/e5/{item}/model_weights.pth'))
        pred_RML_e5_all[idx] = model_RML_e5(test_set_points)
        loss_RML_e5_all[p,idx] = loss(pred_RML_e5_all[idx], test_set_solution)

    loss_ML_inf[p] = loss(model_ML_inf(test_set_points), test_set_solution)
    loss_ML_inf_reg[p] = loss(model_ML_inf_reg(test_set_points), test_set_solution)
    loss_ML_inf_reg_10[p] = loss(model_ML_inf_reg_10(test_set_points), test_set_solution)
    loss_MAP_e4[p] = loss(model_MAP_e4(test_set_points), test_set_solution)
    loss_MAP_e4_R100[p] = loss(model_MAP_e4_R100(test_set_points), test_set_solution)
    loss_MAP_e5[p] = loss(model_MAP_e5(test_set_points), test_set_solution)
    loss_MAP_e6[p] = loss(model_MAP_e6(test_set_points), test_set_solution)
    loss_MAP_e6_R100[p] = loss(model_MAP_e6_R100(test_set_points), test_set_solution)

    loss_RML_e4_0[p] = loss(pred_RML_e4_all[0], test_set_solution)
    loss_RML_e4_n_mean[p] = torch.mean(loss_RML_e4_all[p], dim=0)
    loss_RML_e4_mean[p] = loss(torch.mean(pred_RML_e4_all, dim=0), test_set_solution)
    loss_RML_e4_median[p] = loss(torch.median(pred_RML_e4_all, dim=0)[0], test_set_solution)
    loss_RML_e4_variance[p] = torch.mean(torch.var(pred_RML_e4_all, dim=0))

    loss_RML_e5_0[p] = loss(pred_RML_e5_all[0], test_set_solution)
    loss_RML_e5_n_mean[p] = torch.mean(loss_RML_e5_all[p], dim=0)
    loss_RML_e5_mean[p] = loss(torch.mean(pred_RML_e5_all, dim=0), test_set_solution)
    loss_RML_e5_median[p] = loss(torch.median(pred_RML_e5_all, dim=0)[0], test_set_solution)
    loss_RML_e5_variance[p] = torch.mean(torch.var(pred_RML_e5_all, dim=0))

    loss_MAP_e4_0[p] = loss(model_MAP_e4_0(test_set_points), test_set_solution)
    loss_MAP_e4_1[p] = loss(model_MAP_e4_1(test_set_points), test_set_solution)
    loss_MAP_e4_2[p] = loss(model_MAP_e4_2(test_set_points), test_set_solution)
    loss_MAP_e4_3[p] = loss(model_MAP_e4_3(test_set_points), test_set_solution)
    loss_MAP_e4_4[p] = loss(model_MAP_e4_4(test_set_points), test_set_solution)

    loss_MAP_e5_0[p] = loss(model_MAP_e5_0(test_set_points), test_set_solution)
    loss_MAP_e5_1[p] = loss(model_MAP_e5_1(test_set_points), test_set_solution)
    loss_MAP_e5_2[p] = loss(model_MAP_e5_2(test_set_points), test_set_solution)
    loss_MAP_e5_3[p] = loss(model_MAP_e5_3(test_set_points), test_set_solution)
    loss_MAP_e5_4[p] = loss(model_MAP_e5_4(test_set_points), test_set_solution)

In [22]:
loss_RML_e4_all.shape
print(torch.min(loss_RML_e4_all[0]))
print(torch.min(loss_RML_e4_all, dim=1)[0])
print(torch.quantile(loss_RML_e4_all, 0.1, dim=1))
print(torch.quantile(loss_RML_e4_all[0], 0.1))
print(torch.quantile(loss_RML_e4_all, 0.5, dim=1))
print(torch.quantile(loss_RML_e4_all, 0.9, dim=1))
print(torch.max(loss_RML_e4_all, dim=1)[0])

tensor(2589.1177, grad_fn=<MinBackward1>)
tensor([2589.1177,  635.2662,  496.7845,  409.7758,  283.2042,  181.3043],
       grad_fn=<MinBackward0>)
tensor([3160.9712,  702.9885,  537.4078,  448.8858,  314.5657,  210.7247],
       grad_fn=<SqueezeBackward3>)
tensor(3160.9712, grad_fn=<SqueezeBackward3>)
tensor([3652.0906,  839.3186,  591.0293,  490.6874,  351.7557,  237.7041],
       grad_fn=<SqueezeBackward3>)
tensor([4539.4575, 1162.2141,  744.5953,  578.3859,  390.0454,  274.4622],
       grad_fn=<SqueezeBackward3>)
tensor([5569.9990, 1578.6849,  877.0135,  625.9697,  429.1646,  290.1434],
       grad_fn=<MaxBackward0>)


In [23]:
title = f'{"Model/statistic":15} | {"1 point":8} | {"2 points":8} | {"3 points":8} | {"4 points":8} | {"5 points":8} | {"6 points":8} |'

string_ML_inf = f'{"ML-inf":15} |'
#string_ML_inf_reg = f'{"ML-inf-reg":15} | {"inf":4} |'
string_ML_inf_reg = f'{"MAP-inf":15} |'

string_MAP_e4 = f'{"MAP-e4":15} |'
string_MAP_e5 = f'{"MAP-e5":15} |'

string_MAP_e4_0 = f'{"MAP-e4":15} |'
string_MAP_e4_1 = f'{"MAP-e4":15} |'
string_MAP_e4_2 = f'{"MAP-e4":15} |'
string_MAP_e4_3 = f'{"MAP-e4":15} |'
string_MAP_e4_4 = f'{"MAP-e4":15} |'

string_MAP_e5_0 = f'{"MAP-e5":15} |'
string_MAP_e5_1 = f'{"MAP-e5":15} |'
string_MAP_e5_2 = f'{"MAP-e5":15} |'
string_MAP_e5_3 = f'{"MAP-e5":15} |'
string_MAP_e5_4 = f'{"MAP-e5":15} |'


for i in range(max_points):

    string_ML_inf += f' {loss_ML_inf[i]:8.2f} |' 
    string_ML_inf_reg += f' {loss_ML_inf_reg[i]:8.2f} |' 

    string_MAP_e4 += f' {loss_MAP_e4[i]:8.2f} |' 
    string_MAP_e5 += f' {loss_MAP_e5[i]:8.2f} |' 

    string_MAP_e4_0 += f' {loss_MAP_e4_0[i]:8.2f} |' 
    string_MAP_e4_1 += f' {loss_MAP_e4_1[i]:8.2f} |' 
    string_MAP_e4_2 += f' {loss_MAP_e4_2[i]:8.2f} |' 
    string_MAP_e4_3 += f' {loss_MAP_e4_3[i]:8.2f} |' 
    string_MAP_e4_4 += f' {loss_MAP_e4_4[i]:8.2f} |' 

    string_MAP_e5_0 += f' {loss_MAP_e5_0[i]:8.2f} |' 
    string_MAP_e5_1 += f' {loss_MAP_e5_1[i]:8.2f} |' 
    string_MAP_e5_2 += f' {loss_MAP_e5_2[i]:8.2f} |' 
    string_MAP_e5_3 += f' {loss_MAP_e5_3[i]:8.2f} |' 
    string_MAP_e5_4 += f' {loss_MAP_e5_4[i]:8.2f} |' 

string_break = '-'*83
total_string = ""

print(title); total_string+=title+'\n'
print(string_break); total_string+=string_break+'\n'
print(string_ML_inf); total_string+=string_ML_inf+'\n'
print(string_ML_inf_reg); total_string+=string_ML_inf_reg+'\n'
print(string_break); total_string+=string_break+'\n'

print(string_MAP_e4); total_string+=string_MAP_e4+'\n'
print(string_MAP_e5); total_string+=string_MAP_e5+'\n'
print(string_break); total_string+=string_break+'\n'
print(string_MAP_e4_0); total_string+=string_MAP_e4_0+'\n'
print(string_MAP_e4_1); total_string+=string_MAP_e4_1+'\n'
print(string_MAP_e4_2); total_string+=string_MAP_e4_2+'\n'
print(string_MAP_e4_3); total_string+=string_MAP_e4_3+'\n'
print(string_MAP_e4_4); total_string+=string_MAP_e4_4+'\n'
print(string_break); total_string+=string_break+'\n'
print(string_MAP_e5_0); total_string+=string_MAP_e5_0+'\n'
print(string_MAP_e5_1); total_string+=string_MAP_e5_1+'\n'
print(string_MAP_e5_2); total_string+=string_MAP_e5_2+'\n'
print(string_MAP_e5_3); total_string+=string_MAP_e5_3+'\n'
print(string_MAP_e5_4); total_string+=string_MAP_e5_4+'\n'
print(string_break); total_string+=string_break+'\n'

Model/statistic | 1 point  | 2 points | 3 points | 4 points | 5 points | 6 points |
-----------------------------------------------------------------------------------
ML-inf          |   625.19 |    65.79 |   192.65 |   144.46 |    77.31 |    37.18 |
MAP-inf         |   443.55 |    41.70 |   150.94 |   100.98 |    47.48 |    22.96 |
-----------------------------------------------------------------------------------
MAP-e4          |  1257.94 |   140.77 |   207.49 |   153.29 |    82.61 |    39.82 |
MAP-e5          |   936.00 |   114.62 |   208.32 |   162.86 |    79.37 |    36.78 |
-----------------------------------------------------------------------------------
MAP-e4          |  1861.60 |   240.82 |   253.37 |   200.29 |   113.24 |    52.31 |
MAP-e4          |  1698.63 |   186.28 |   224.47 |   174.53 |    98.46 |    48.55 |
MAP-e4          |  1582.35 |   139.73 |   198.12 |   162.89 |    92.28 |    44.75 |
MAP-e4          |  1717.70 |   213.89 |   236.03 |   180.09 |    99.55 |    

In [24]:
#with open('../figures/plot_table_prediction_error/plot_table_prediction_error.txt', 'w') as outfile:
#    outfile.write('\n\n' + total_string[:-1])

In [25]:
title = f'{"Model":15} | {"1 point":8} | {"2 points":8} | {"3 points":8} | {"4 points":8} | {"5 points":8} | {"6 points":8} |'
total_string = ""
print(title); total_string+=title+'\n'
print(string_break); total_string+=string_break+'\n'
print(string_ML_inf); total_string+=string_ML_inf+'\n'
print(string_ML_inf_reg); total_string+=string_ML_inf_reg+'\n'
print(string_break); total_string+=string_break+'\n'

#print(string_MAP_e4); total_string+=string_MAP_e4+'\n'
#print(string_MAP_e5); total_string+=string_MAP_e5+'\n'
#print(string_break); total_string+=string_break+'\n'
#with open('../figures/plot_table_prediction_error/plot_table_prediction_error_inf.txt', 'w') as outfile_inf:
#    outfile_inf.write(total_string[:-1])

Model           | 1 point  | 2 points | 3 points | 4 points | 5 points | 6 points |
-----------------------------------------------------------------------------------
ML-inf          |   625.19 |    65.79 |   192.65 |   144.46 |    77.31 |    37.18 |
MAP-inf         |   443.55 |    41.70 |   150.94 |   100.98 |    47.48 |    22.96 |
-----------------------------------------------------------------------------------


In [26]:

title = f'{"Model":15} | {"1 point":8} | {"2 points":8} | {"3 points":8} | {"4 points":8} | {"5 points":8} | {"6 points":8} |'
total_string = ""
print(title); total_string+=title+'\n'
print(string_break); total_string+=string_break+'\n'
#print(string_ML_inf); total_string+=string_ML_inf+'\n'
#print(string_ML_inf_reg); total_string+=string_ML_inf_reg+'\n'
#print(string_break); total_string+=string_break+'\n'

print(string_MAP_e4); total_string+=string_MAP_e4+'\n'
print(string_MAP_e5); total_string+=string_MAP_e5+'\n'
print(string_break); total_string+=string_break+'\n'
#with open('../figures/plot_table_prediction_error/plot_table_prediction_error_map.txt', 'w') as outfile_inf:
#    outfile_inf.j(total_string[:-1])

Model           | 1 point  | 2 points | 3 points | 4 points | 5 points | 6 points |
-----------------------------------------------------------------------------------
MAP-e4          |  1257.94 |   140.77 |   207.49 |   153.29 |    82.61 |    39.82 |
MAP-e5          |   936.00 |   114.62 |   208.32 |   162.86 |    79.37 |    36.78 |
-----------------------------------------------------------------------------------


In [27]:
#with open('../figures/plot_table_prediction_error/plot_table_prediction_error_inf.txt', 'w') as outfile:
#    outfile.write(total_string[:-1])

In [28]:

title = f'{"Percentile":15} | {"1 point":8} | {"2 points":8} | {"3 points":8} | {"4 points":8} | {"5 points":8} | {"6 points":8} |'
title2 = f'{"Mean":15} {"":65} |'

loss_RML_e4_all.shape
#print(torch.min(loss_RML_e4_all, dim=1)[0])
#print(torch.quantile(loss_RML_e4_all, 0.1, dim=1))
#print(torch.quantile(loss_RML_e4_all, 0.5, dim=1))
#print(torch.quantile(loss_RML_e4_all, 0.9, dim=1))
#print(torch.max(loss_RML_e4_all, dim=1)[0])

string_RML_e4_min = f'{"RML-e4-min":15} |'
string_RML_e4_p10 = f'{"RML-e4-p10":15} |'
string_RML_e4_p50 = f'{"RML-e4-p50":15} |'
string_RML_e4_p90 = f'{"RML-e4-p90":15} |'
string_RML_e4_max = f'{"RML-e4-max":15} |'

string_RML_e5_min = f'{"RML-e5-min":15} |'
string_RML_e5_p10 = f'{"RML-e5-p10":15} |'
string_RML_e5_p50 = f'{"RML-e5-p50":15} |'
string_RML_e5_p90 = f'{"RML-e5-p90":15} |'
string_RML_e5_max = f'{"RML-e5-max":15} |'


for i in range(max_points):

    string_RML_e4_min += f' {torch.min(loss_RML_e4_all[i]):8.2f} |' 
    string_RML_e4_p10 += f' {torch.quantile(loss_RML_e4_all[i], 0.1):8.2f} |'
    string_RML_e4_p50 += f' {torch.quantile(loss_RML_e4_all[i], 0.5):8.2f} |'
    string_RML_e4_p90 += f' {torch.quantile(loss_RML_e4_all[i], 0.9):8.2f} |'
    string_RML_e4_max += f' {torch.max(loss_RML_e4_all[i]):8.2f} |' 

    string_RML_e5_min += f' {torch.min(loss_RML_e5_all[i]):8.2f} |' 
    string_RML_e5_p10 += f' {torch.quantile(loss_RML_e5_all[i], 0.1):8.2f} |'
    string_RML_e5_p50 += f' {torch.quantile(loss_RML_e5_all[i], 0.5):8.2f} |'
    string_RML_e5_p90 += f' {torch.quantile(loss_RML_e5_all[i], 0.9):8.2f} |'
    string_RML_e5_max += f' {torch.max(loss_RML_e5_all[i]):8.2f} |' 


string_break = '-'*83
total_string = ""

print(title); total_string+=title+'\n'
print(string_break); total_string+=string_break+'\n'

print(string_RML_e4_min); total_string+=string_RML_e4_min+'\n'
print(string_RML_e4_p10); total_string+=string_RML_e4_p10+'\n'
print(string_RML_e4_p50); total_string+=string_RML_e4_p50+'\n'
print(string_RML_e4_p90); total_string+=string_RML_e4_p90+'\n'
print(string_RML_e4_max); total_string+=string_RML_e4_max+'\n'

print(string_break); total_string+=string_break+'\n'

print(string_RML_e5_min); total_string+=string_RML_e5_min+'\n'
print(string_RML_e5_p10); total_string+=string_RML_e5_p10+'\n'
print(string_RML_e5_p50); total_string+=string_RML_e5_p50+'\n'
print(string_RML_e5_p90); total_string+=string_RML_e5_p90+'\n'
print(string_RML_e5_max); total_string+=string_RML_e5_max+'\n'

print(string_break); total_string+=string_break+'\n'
print(title2); total_string+=title2+'\n'
print(string_break); total_string+=string_break+'\n'
print(string_RML_e4_n_mean); total_string+=string_RML_e4_n_mean+'\n'
print(string_RML_e5_n_mean); total_string+=string_RML_e5_n_mean+'\n'
print(string_break); total_string+=string_break+'\n'

Percentile      | 1 point  | 2 points | 3 points | 4 points | 5 points | 6 points |
-----------------------------------------------------------------------------------
RML-e4-min      |  2589.12 |   635.27 |   496.78 |   409.78 |   283.20 |   181.30 |
RML-e4-p10      |  3160.97 |   702.99 |   537.41 |   448.89 |   314.57 |   210.72 |
RML-e4-p50      |  3652.09 |   839.32 |   591.03 |   490.69 |   351.76 |   237.70 |
RML-e4-p90      |  4539.46 |  1162.21 |   744.60 |   578.39 |   390.05 |   274.46 |
RML-e4-max      |  5570.00 |  1578.68 |   877.01 |   625.97 |   429.16 |   290.14 |
-----------------------------------------------------------------------------------
RML-e5-min      |   764.14 |   137.17 |   214.30 |   168.21 |    95.45 |    53.94 |
RML-e5-p10      |  1192.08 |   162.77 |   234.48 |   178.87 |   104.38 |    56.94 |
RML-e5-p50      |  1647.35 |   223.89 |   254.97 |   194.59 |   114.50 |    63.98 |
RML-e5-p90      |  2325.18 |   295.19 |   279.71 |   215.05 |   132.38 |    

NameError: name 'string_RML_e4_n_mean' is not defined

In [ ]:

#with open('../figures/plot_table_prediction_error/plot_table_percentile.txt', 'w') as outfile:
#    outfile.write(total_string[:-1])

Model           | N train data | Regularization | Comment                            |
--------------------------------------------------------------------------------------
ML-inf          | Infinite     | None           | Maximum likelihood model           |
MAP-inf         | Infinite     | L_2            | Model with L_2 regularization      |
MAP-e4          | 10^4         | L_2            | L_2 reg. trained with 10^4 data    |
MAP-e5          | 10^5         | L_2            | L_2 reg. trained with 10^5 data    |
RML-e4-1        | 10^4         | L_2 (RML)      | RML model number 1 with 10^4 data  |
RML-e5-1        | 10^5         | L_2 (RML)      | RML model number 1 with 10^5 data  |
--------------------------------------------------------------------------------------
Statistic       |              |                | Comment                            |
--------------------------------------------------------------------------------------
RML-e4-n-mean   |              |           

In [ ]:

title = f'{"Model":15} | {"1 point":8} | {"2 points":8} | {"3 points":8} | {"4 points":8} | {"5 points":8} | {"6 points":8} |'

total_string = ""
print(title); total_string+=title+'\n'
print(string_break); total_string+=string_break+'\n'
print(string_RML_e4_n_mean); total_string+=string_RML_e4_n_mean+'\n'
print(string_RML_e5_n_mean); total_string+=string_RML_e5_n_mean+'\n'
print(string_break); total_string+=string_break+'\n'

#print(string_MAP_e4); total_string+=string_MAP_e4+'\n'
#print(string_MAP_e5); total_string+=string_MAP_e5+'\n'
#print(string_break); total_string+=string_break+'\n'
#with open('../figures/plot_table_prediction_error/plot_table_prediction_error_RML_n.txt', 'w') as outfile_inf:
#    outfile_inf.write(total_string[:-1])

Model           | 1 point  | 2 points | 3 points | 4 points | 5 points | 6 points |
-----------------------------------------------------------------------------------


NameError: name 'string_RML_e4_n_mean' is not defined